version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "composer.json" }}
            - v2-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ~/.composer/cache
            - ./vendor
          key: v2-dependencies-{{ checksum "composer.json" }}

      - run: vendor/bin/phpcs -p
